def generate_markdown(sector, analysis):

    report = f"""
# 📊 Market Analysis Report

## 🏭 Sector
**{sector.title()}**

---

## 📈 Analysis
{analysis}

---

## 🔎 Generated By
Trade Opportunities API (FastAPI + Gemini AI)

"""
    return report